name: Build Jemalloc Java Images
on:
  schedule:
    - cron: "0 0 * * 1"
  workflow_dispatch:
  push:

jobs:
  push:
    name: "pterodactyl-images:bullseye-jemalloc-java-${{ matrix.tag }}"
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        tag:
          - 19-jre
          - 19-jdk
    steps:
      - uses: actions/checkout@v2
      - name: Generate Dockerfile
        working-directory: ./java
        run: ./java/gendocker.sh ${{ matrix.tag }}
        shell: bash
      - uses: docker/setup-buildx-action@v1
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Publish to GitHub Container Registry
        uses: docker/build-push-action@v2
        with:
          context: ./java/build
          file: ./java/build/Dockerfile
          platforms: linux/amd64
          push: true
          tags: |
            ghcr.io/greysilly7/pterodactyl-java:bullseye-jemalloc-${{ matrix.tag }}
